### ISSUE TITLE
Creation of an EU vocabulary on life events

### ISSUE THREAD

**Issue by GabrieleCiasullo** [SEMICeu/Taxonomy#3]
In order to define a common classification of public services, also based on the Annex II of SDG Regulation, it needs the creation of a specific vocabulary on life events (including both citizen and business events) to be published in the context of the EU vocabularies by EU Publications Office. That vocabulary should be intended in addition to the pattern and could be useful to facilitate the search of PSs by the users .

**Comment by kareljanr** [comment]
Hi Gabriele,
a vocabulary of life events was created already. You can find it in the CPSV-AP specification here:
https://joinup.ec.europa.eu/release/core-public-service-vocabulary-application-profile/221

I do agree with you that it needs to be published by the Publications Office.

If you have any comment on the lists of life events, please do so.
Thank you for your comment!

**Comment by barthanssens** [comment]
Do you know if the publication on the EU Publication Office is ongoing ?
Or do we (EU Member States) have to submit some kind of  formal request ? Thanks

**Comment by GabrieleCiasullo** [comment]
Dear Bart,

I don’t believe that the Publications Office is publishing the life-event taxonomy, but I am certainly available to make a formal request, in the context of the activities related to the implementation of the SDG Rules.

                Best,
                Gabriele


---------------------------------
[cid:image003.jpg@01D3FE8A.4986CF70]
Gabriele Ciasullo
Area architetture, standard e infrastrutture
Responsabile Servizio Banche dati e Open data
Via Liszt, 21 - 00144 Roma
e-mail: ciasullo@agid.gov.it<mailto:ciasullo@agid.gov.it>
Tel. 06.85264285
Mobile 329.8524671
www.agid.gov.it<http://www.agid.gov.it/>



Da: Bart Hanssens <notifications@github.com>
Inviato: giovedì 28 novembre 2019 14:28
A: catalogue-of-services-isa/Taxonomy <Taxonomy@noreply.github.com>
Cc: CIASULLO Gabriele <ciasullo@agid.gov.it>; Author <author@noreply.github.com>
Oggetto: Re: [catalogue-of-services-isa/Taxonomy] Creation of an EU vocabulary on life events (#3)


Do you know if the publication on the EU Publication Office is ongoing ?
Or do we (EU Member States) have to submit some kind of formal request ? Thanks

**Comment by kareljanr** [comment]
Dear Bart,
Dear Gabriele,

Please do submit formal request here. We are in contact with the Publication's Office (OP) in order to publish different controlled vocabularies as SKOS. Please check the [CPSV-AP specification](https://joinup.ec.europa.eu/solution/core-public-service-vocabulary-application-profile/distribution/cpsv-ap-specification-v221-pdf), chapter 4, recommended controlled vocabularies for controlled vocabularies that seems useful to you to publish in SKOS by the OP. 

Some examples:
- Business Event type

- Life Event type

- Output type

- Channel type

**Comment by barthanssens** [comment]
That's very good news.

In Belgium, we'd like to at least have the Business Event Types (1st/2nd level) and the Life Event Types published by EU Publication Office



As a more broader request (I realize this will be probably out of scope for the Core Vocabularies), we will soon (have to) use a common model for exchanging Single Digital Gateway info - hopefully CPSV-AP - where [Annex I and II](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=uriserv:OJ.L_.2018.295.01.0001.01.ENG&toc=OJ:L:2018:295:TOC) include lists of 'information areas' and 'procedures'
These could/should also be published as SKOS (also EU PO ? another service ?) and/or preferably be mapped to, or integrated into the CPSV-AP events. But I guess I'd better repeat that request to the SDG wiki

**Comment by costezki** [comment]
The Standardisation and Metadata unit (A1) is more than happy to support and publish taxonomies and controlled vocabularies for standardization purposes. 

When you have the vocabularies ready, provide them to us and we will publish them on EU Vocabularies website. We also push further our asset descriptions to JoinUp, ODP, Bartoc and soon WikiData. 

The best is to express them in SRC-AP (the application profile based on SKOS tailored for maintaining the data in VocBench3) or SKOS core/XL. Documentation of SRC-AP application profile is found here
https://github.com/eu-vocabularies/SKOS-AP-EU/blob/master/src-ap-vb3/doc/src-ap-vb3.pdf

If you have any further questions please do not hesitate to contact us directly.

**Comment by EmidioStani** [comment]
Hello @costezki , I am looking at the specification and I have a question:

I see in skosxl:Label 2 mandatory properties (lexinfo:animacy and lexinfo:formNumberVariant), I don't know how to use them and I didn't find examples in the authority tables (https://op.europa.eu/en/web/eu-vocabularies/authority-tables)

Thanks for let me know

**Comment by costezki** [comment]
Indeed Emidio, thank you for pointing it out. 
That is a mistake and will be updated to cardinality [0..1 ]. 
Grammatical features are optional and currently used in a few authority tables only.

**Comment by EmidioStani** [comment]
Dear @GabrieleCiasullo and @barthanssens ,

a file [Business_Life-Events_controlled_vocabulary_v1.00.xlsx]( https://github.com/SEMICeu/Taxonomy/blob/master/Business_Life-Events_controlled_vocabulary_v1.00.xlsx) has been uploaded with the main business and life events merging the initial list of CPSV-AP with those coming from SDG.

An explanation of the file can be found in the [readme](https://github.com/SEMICeu/Taxonomy/blob/master/README.md#business-and-life-event-taxonomy-file)

The intention is to review with the working group and present it to the Publications Office

**Comment by barthanssens** [comment]
Ok, thanks !

**Comment by EmielDh** [comment]
The publications office has release the [Business events](https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/business-event) and [Life Events](https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/life-event) code lists.
